[install]
# Use exact versions for better reproducibility
exact = true

[install.cache]
# Enable caching for faster installs
dir = ".bun"

[test]
# Test configuration
preload = ["./src/test/setup.ts"]

[run]
# Run configuration
bun = true
